id: hl7.fhir.dk.smart
canonical: http://hl7.dk/fhir/smart
name: DKSmart
title: Danish Implementation Guide for SMART App Launch 
description: Guidelines for using the SMART App Launch mechanism in Denmark.
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#DK "Denmark" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 Denmark
  url: https://www.hl7.dk/
  email: jenskristianvilladsen@gmail.com

dependencies:
  hl7.fhir.uv.ipa: 1.0.0
  hl7.fhir.uv.smart-app-launch: 2.2.0

resources:
  CapabilityStatement/example-ipa-server:
    exampleBoolean: true
    name: IPA Server Example
    description: An example CapabilityStatement
    exampleCanonical: http://hl7.dk/fhir/smart/StructureDefinition/dk-smart-server-profile

pages:
  index.md:
    title: Home
  conformance.md:
    title: Conformance
  examples.md:
    title: Examples
  downloads.md:
    title: Downloads
  
parameters:
  ipa-comparison: "{last}"
  

menu:
  Home: index.html
  Conformance: conformance.html
  Examples: examples.html
  Artifacts: artifacts.html
  Downloads: downloads.html


# ╭────────────────────────────────────────────releasing───────────────────────────────────────────╮
# │  Variables for release control                                                                 │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

version: 1.0.0
#Flip status to 'active' for publication. Flip to 'draft' for CI
#status: draft
status: active
#Flip releaseLabel to 'release' for publication. Flip to 'ci-build' for CI
#releaseLabel: ci-build
releaseLabel: trial-use